server:
  port: 8080
  servlet:
    context-path: /springbootb9wc1

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.205.233.141/springbootb9wc1?useSSL=false&useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
    username: springbootb9wc1
    password: Lzq12345
    hikari:
      max-lifetime: 1800000
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  data:
    redis:
      host: 60.205.233.141
      port: 6379
      password: Lzq12345
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.entity
  global-config:
    id-type: 1
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

