server:
  port: 8080
  servlet:
    context-path: /springbootb9wc1

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.205.233.141/fake_tiktok?useSSL=false&useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: L@z@q1065
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  data:
    redis:
      host: 60.205.233.141
      port: 6379
      password: Lzq12345
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.entity
  global-config:
    id-type: 1
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  oss:
    bucketName: fake-tiktok
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5t8x1rtcGWJbYyTTmSNg
    accessKeySecret: x05bWMNZOkb0jQNmCa9JhlMvEcDY3H

management:
  endpoints:
    web:
      exposure:
        include: "*"
